sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 2453
    database: delivery
    username: root
    password: 324Wangsiyi@
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLXFvviwFwadM93gSxz
    access-key-secret: bJAp2kYwALSPCEySFEPM2m5OLTacld
    bucket-name: w0sy